name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Write key
      run: |
        if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
          {
            echo storePassword="${{ secrets.KEYSTORE_PASSWORD }}"
            echo keyPassword="${{ secrets.KEY_PASSWORD }}"
            echo keyAlias="${{ secrets.KEY_ALIAS }}"
            echo storeFile="../keystore.jks"
          } > keystore.properties
          echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease
         
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: app/build/outputs/apk/release/*.apk
